version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - ${PORT_IN_HOST_MAP}:3000
